# Generated by Django 4.2.17 on 2024-12-17 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account_app', '0002_alter_user_instancy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uid')),
                ('name', models.CharField(max_length=100)),
                ('satelit_serial', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='zoo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zoo_model', to=settings.AUTH_USER_MODEL)),
                ('instancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.instancy')),
            ],
            options={
                'db_table': 'collar_zoo',
            },
        ),
        migrations.CreateModel(
            name='SensorDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=11, null=True)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=11, null=True)),
                ('temperature', models.FloatField(null=True)),
                ('battery', models.FloatField(null=True)),
                ('zoo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sensor_data', to='api_app.zoo')),
            ],
            options={
                'db_table': 'collar_sensor_data',
                'unique_together': {('zoo', 'time')},
            },
        ),
    ]
