# Generated by Django 5.1.7 on 2025-07-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawSensorDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('topik', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'collar_raw_sensor_data',
                'unique_together': {('message', 'time')},
            },
        ),
    ]
