# Generated by Django 5.1.7 on 2025-07-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_rawsensordatamodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawsensordatamodel',
            old_name='topik',
            new_name='topic',
        ),
    ]
