# Generated by Django 5.1.7 on 2025-07-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_rename_topik_rawsensordatamodel_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=11, null=True)),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=11, null=True)),
                ('radius_km', models.FloatField()),
                ('place_name', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collar_area',
                'unique_together': {('longitude', 'latitude')},
            },
        ),
    ]
