# Generated by Django 5.1.7 on 2025-07-07 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_alter_areamodel_latitude_alter_areamodel_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areamodel',
            name='latitude',
            field=models.DecimalField(decimal_places=11, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='areamodel',
            name='longitude',
            field=models.DecimalField(decimal_places=11, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='sensordatamodel',
            name='latitude',
            field=models.DecimalField(decimal_places=11, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='sensordatamodel',
            name='longitude',
            field=models.DecimalField(decimal_places=11, max_digits=16, null=True),
        ),
    ]
