# Generated by Django 5.1.7 on 2025-07-13 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_alter_areamodel_latitude_alter_areamodel_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawsensordatamodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensordatamodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
