# Generated by Django 5.1.7 on 2025-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_alter_rawsensordatamodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('bot_name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
