# Generated by Django 5.1.7 on 2025-07-23 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0004_alter_user_role'),
        ('api_app', '0008_telegrammodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordatamodel',
            old_name='battery',
            new_name='distance_from_node',
        ),
        migrations.RenameField(
            model_name='sensordatamodel',
            old_name='temperature',
            new_name='rssi',
        ),
        migrations.RenameField(
            model_name='zoo',
            old_name='satelit_serial',
            new_name='node_serial',
        ),
        migrations.CreateModel(
            name='GatewayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('serial_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uid')),
                ('latitude', models.DecimalField(decimal_places=11, max_digits=16, null=True)),
                ('longitude', models.DecimalField(decimal_places=11, max_digits=16, null=True)),
                ('gateway_serial', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateway_model', to=settings.AUTH_USER_MODEL)),
                ('instancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account_app.instancy')),
            ],
            options={
                'db_table': 'collar_gateway',
            },
        ),
    ]
