# Generated by Django 5.1.7 on 2025-07-23 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_rename_battery_sensordatamodel_distance_from_node_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordatamodel',
            old_name='distance_from_node',
            new_name='distance_from_gateway',
        ),
        migrations.AddField(
            model_name='sensordatamodel',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_app.gatewaymodel'),
        ),
    ]
