# Generated by Django 5.1.7 on 2025-07-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0002_alter_user_instancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='instancy',
            name='pic_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
