# Generated by Django 5.1.7 on 2025-07-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_app', '0003_instancy_pic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'SuperAdmin'), (2, 'Admin'), (3, 'Guest')], default=1),
        ),
    ]
